### ISSUE TITLE
[Bug] Heroku Internal Server Error

### ISSUE THREAD

**Issue by eapostol** [UTBootCampGroup2Project2/reward-bank#59]
As a parent user, when I attempt to create / add a 'child' user, I should be enabled to do so.

![Screen Shot 2021-04-14 at 11 47 31 AM](https://user-images.githubusercontent.com/565104/114741069-6be6dd00-9d18-11eb-877e-9fd33cf5fcb3.png)

Expected Result:

I should see a view that is expected to  give me a new 'child user'.

Actual Result:

I get a server error (see diagram above)

**Comment by eapostol** [comment]
![Screen Shot 2021-04-14 at 11 59 28 AM](https://user-images.githubusercontent.com/565104/114741579-e6aff800-9d18-11eb-8b16-695857b13874.png)

Note network error, may be a cross-domain policy issue . likely tested against localhost only and utilizing a domain name is not resolved.

**Comment by BrianCKWang** [comment]
This is most likely due to the duplicated username (parent username is edward and attempted child username is also edward as shown in the picture) which is showing as an internal server error. Will add in more descriptive error message.

**Comment by BrianCKWang** [comment]
Resolved. 
Now user will be alerted when registering with a username that already exists in the database.
