### ISSUE TITLE
[Issue] Revealing console logs present potential security issue

### ISSUE THREAD

**Issue by eapostol** [UTBootCampGroup2Project2/reward-bank#60]
As a user, I should not be able to see console.log() or related statements that may reveal how the application works.
It presents a security risk. The image also reveals content related to previously submitted bug regarding heroku error

![Screen Shot 2021-04-14 at 12 00 50 PM](https://user-images.githubusercontent.com/565104/114741888-35f62880-9d19-11eb-9f45-3317edc44631.png)

**Comment by BrianCKWang** [comment]
Resolved
